# Generated by Django 3.1.1 on 2020-10-11 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('sku', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('common_brand', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('order', models.IntegerField()),
                ('total', models.FloatField()),
                ('no_of_items', models.IntegerField()),
                ('manufactured_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('side_effects', models.TextField(max_length=200)),
                ('how_to_use', models.TextField(max_length=200)),
                ('img1', models.FileField(null=True, upload_to='media')),
                ('img2', models.FileField(null=True, upload_to='media')),
                ('img3', models.FileField(null=True, upload_to='media')),
            ],
            options={
                'db_table': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('bdate', models.DateField()),
                ('gender', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.person')),
                ('date_registered', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100)),
                ('spouse_name', models.CharField(max_length=100)),
                ('spouse_occupation', models.CharField(max_length=100)),
                ('no_children', models.IntegerField()),
                ('mothers_name', models.CharField(max_length=100)),
                ('mothers_occupation', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('fathers_occupation', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('religion', models.CharField(max_length=100)),
                ('profile_pic', models.FileField(null=True, upload_to='media')),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('customer.person',),
        ),
        migrations.CreateModel(
            name='CustomerAcquiresMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicine', to='customer.medicine')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='customer.customer')),
            ],
            options={
                'db_table': 'CustomerAcquired',
            },
        ),
    ]
