# Generated by Django 3.1.1 on 2020-10-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='total',
        ),
    ]
